### ISSUE TITLE
Not actually calling `isSufficientlyFilled`

### ISSUE THREAD

**Issue by jabr** [marcelklehr/smokesignal#16]
It looks like this line is wrong:

https://github.com/marcelklehr/smokesignal/blob/develop/lib/node.js#L140

```
if(!this.peers.isSufficientlyFilled) {
```

It looks like that should be:

```
if(!this.peers.isSufficientlyFilled()) {
```

**Comment by marcelklehr** [comment]
Yes, indeed. Nice catch!

**Comment by jabr** [comment]
I'll send you a PR.
