### ISSUE TITLE
How is the peerlist used ?

### ISSUE THREAD

**Issue by sethleedy** [marcelklehr/smokesignal#21]
I need an example to get myself going.
node.peerlist is showing as undefined...

**Comment by marcelklehr** [comment]
Oh, good catch! That's a bug in the README. It should be node.peers:
```
node.peers.on('add', (peer) => {
  peer.write('hello!')
})
```

**Comment by sethleedy** [comment]
Would I do something similar for reading ? Your readme does not really touch that. peer.read ?

**Comment by marcelklehr** [comment]
Peer is a subclass of a node duplex stream ;)
