### ISSUE TITLE
How to connect 2 computers?

### ISSUE THREAD

**Issue by borysfranko11** [marcelklehr/smokesignal#24]
I installed smokesignal on 2 computers and run node peer.js
I gave each ip address like 192.168.2.3 for 1st com, 192.168.2.12 for 2nd com.
Seed 192.168.2.100, port num is 192.168.2.100

After run node peer.js command, it shows connecting message... and then nothing happen.. 
Give me help

**Comment by marcelklehr** [comment]
> Seed 192.168.2.100, port num is 192.168.2.100

Usage of smokesignal requires basic knowledge about computer networks and decentralized networking. Here are some pointers: The port number you supplied is invalid. You need to have smokesignal running on the computer with the IP given as seed.

**Comment by borysfranko11** [comment]
Ah.. sorry.. i gave port num 8496

**Comment by borysfranko11** [comment]
I put the code like this.. 
var node = smoke.createNode({
  port: parseInt(process.argv[2]) || 8496
, address: smoke.localIp('192.168.2.12')
, seeds: [{port: 8496, address:'192.168.2.100'}]
 //<-- You may need to change this address!
})

and run it.. it show only connecting.. message..

**Comment by marcelklehr** [comment]
A network seed is a node that is known "publicly" and accessible at all times. If you don't have smokesignal running at 192.168.2.100:8496 nothing will connect, as the seed is the first thing a node will contact.

**Comment by borysfranko11** [comment]
Have question. 
If i dont input seed , what happen?

**Comment by borysfranko11** [comment]
I am going to build LAN P2P Chat Messenger using smokesignal. 

Please give me guide.. how can i implement it?

**Comment by marcelklehr** [comment]
If you don't provide a seed you will need to connect to a peer manually. see https://github.com/marcelklehr/smokesignal#nodeaddpeeraddressstring-portint

Have you seen https://github.com/marcelklehr/smokesignal/blob/develop/example/ChatApp/peer.js ?

**Comment by borysfranko11** [comment]
Yes.. i Have seen it
But it not working..
if i change my ip address 192.168.1.x on 2 computers. it can be worked?
Also why Seed is needed? 
I am not sure how can i integrate smokesignal into my app.

**Comment by marcelklehr** [comment]
You will need to change these two lines: https://github.com/marcelklehr/smokesignal/blob/develop/example/ChatApp/peer.js#L7-L8

Somehow you need to discover peers. Smokesignal does this by means of static node(s) that you can use to join the network. Discovery is then done within the network. You can also simply not use a seed and try to add peers from mDNS or whatever you prefer.

**Comment by borysfranko11** [comment]
Still same error

![image](https://user-images.githubusercontent.com/33747217/46218666-cc3eea80-c377-11e8-9146-37ffa0abdfe7.png)

**Comment by borysfranko11** [comment]
![image](https://user-images.githubusercontent.com/33747217/46218811-2fc91800-c378-11e8-9f1c-cca23ca14b97.png)
this is code what i did

**Comment by marcelklehr** [comment]
I'd try getting it to work with two peers on the same computer first. You can use two terminals and two ports for that. If you don't use the seed mechanism, comment it out. Otherwise the seed should be an IP and port where another smokesignal node is listening as well. Also, addPeer only tries to add the peer once. It doesn't treat the address like a seed address and constantly tries to connect, but it only tries to connect once. You have to set up the peer at 192.168.2.3:14 first and then run the script that adds it as a peer. Also, as a tip: smoke.localIp can give you the IP address of the current computer without you having to hardcode it. You simply have to provide the subnet. i.e. in your case probably `'192.168.2.0/255.255.255.0'` (see https://en.wikipedia.org/wiki/Subnetwork).

**Comment by borysfranko11** [comment]
I just tried on same computer with different port on 2 terminals.
And  still not working.. 

Run node peer.js 70 on first terminal, Run node peer.js on 2nd terminal.

Still showing Connecting.. message.

**Comment by borysfranko11** [comment]
I tried to add node.addPeer('192.168.2.3, 71) on one of terminal.. 
after that it connected once, and then disconnected suddenly
![image](https://user-images.githubusercontent.com/33747217/46224161-0fa15500-c388-11e8-842d-3e2e5ba8f96f.png)

**Comment by borysfranko11** [comment]
I think peer.js file can not find peers correctly , and can not keep connection each other.

**Comment by marcelklehr** [comment]
A node cannot connect to itself. If you addPeer with the node's own IP, it'll connect at first and then quickly disconnect. Run `node peer 71` *first* (it'll connect with itself, then notice that and disconnect), then start `node peer 72` to connect with port 71.
